#!/bin/sh
# shellcheck disable=SC3040
set -euo pipefail

# Environment Variables
# 環境設定
# 作業ディレクトリを作成して、そこにログファイルをダウンロードするので、/tmp に移動する
export HOME="/tmp"
cd "${HOME}"


# Initialization - load function handler
# shellcheck disable=SC1090,SC2086
. "${LAMBDA_TASK_ROOT}"/"$(echo $_HANDLER | cut -d. -f1).sh"


while true
do
    # Request the next event from the Lambda runtime
    HEADERS="$(mktemp)"
    EVENT_DATA=$(curl -v -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
    INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # Execute the handler function from the script
    RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

    # Send the response to Lambda runtime
    curl -v -sS -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$INVOCATION_ID/response" -d "$RESPONSE"
done